### ISSUE TITLE
Failed to install template dependencies.nsupported platform for fsevents@2.1.3

### ISSUE THREAD

**Issue by MahmoudSharkawy** [monaca/monaca-cli#163]
sorry i new learning what the problem?

```
monaca create tutorial --template onsenui-v2-js-minimum

Downloading template...

[www] Inserting components...
Installing template dependencies...

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

SyntaxError: Unexpected end of JSON input while parsing near '...am":"git+https://gith'
    at JSON.parse (<anonymous>)
    at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  parent: 'cordova-lib'
}
Error occurred while creating project: Failed to install template dependencies.nsupported platform for fsevents@2.1.3: wanted {"o

```

**Comment by yong-asial** [comment]
@iMAHMOD It seems that you are on windows. At the moment, we could not reproduce the problems in our environment. we have tried with Node 10.x, 12.x, and 14.x.

First thing first, the warning is that it could not install `fsevents` package as it doesn't need for windows environment but it should not be the problem.

However, from the build log, there seems to be problem with `cordova-lib` package.

Anyway, please try the following
- Make sure that the permission `C:\Program Files\nodejs\node_modules` is writable 
- Install the latest `monaca-cli` and maybe you can start first testing with Node 10.x (Node 8.x is not recommended)

If the error still exists, please send me the full error log and then try the following steps:
- clone the template from github directly - `git clone git@github.com:monaca-templates/onsenui-v2-js-minimum.git`
- cd `onsenui-v2-js-minimum` and run `npm install` then investigate the error if any
- if you able to install the packages without problem, you just need to run `monaca init` and then you are done.

**Comment by MahmoudSharkawy** [comment]
i Have Node 12 on Win10 
```
 __  __
|  \/  | ___  _ __   __ _  ___ __ _
| |\/| |/ _ \| '_ \ / _` |/ __/ _` |
| |  | | (_) | | | | (_| | (_| (_| |
|_|  |_|\___/|_| |_|\__,_|\___\__,_|

 Command Line Interface for Monaca and Onsen UI
 Monaca CLI Version 3.3.5

Usage: monaca command [args]

  To learn about a specific command type:

  $ monaca <command> --help

Commands: (use --help to show all)

  login  ..........  sign in to Monaca Cloud
  logout  .........  sign out from Monaca Cloud
  signup  .........  register a new Monaca account
  create  .........  create a new local Monaca project from a template
  clone  ..........  clone a project from Monaca Cloud
  import  .........  import a project from Monaca Cloud
  config  .........  manage Monaca configuration
  docs  ...........  display docs for Monaca CLI, Onsen UI and Tutorials
  info  ...........  display project and environment info

Typical Usage:

  $ monaca create myproject # Create a new project from various templates
  $ cd myproject
  $ monaca preview # Preview app on a browser
  $ monaca debug # Run the app in Monaca Debugger
  $ monaca remote build # Execute remote build for packaging
```

same problem after `monaca init`

**Comment by yong-asial** [comment]
@iMAHMOD 

> same problem after monaca init

Could you tell us the error?

> run npm install then investigate the error if any

You didn't mention you have problem with `npm install`. So i assume it went well, right?
